### ISSUE TITLE
Incompatible with autoform 5.0

### ISSUE THREAD

**Issue by tgoorden** [comerc/meteor-autoform-placecomplete#2]
The current package descriptor prevents autoform from being upgraded to 5.0. Not sure if it actually breaks the code though.

**Comment by MaxGuitet** [comment]
Got the same problem with version 5.3.2

**Comment by patrickleet** [comment]
+1

**Comment by mehrdadarvin** [comment]
+1

**Comment by comerc** [comment]
bugfix
